### PR TITLE
Creates attendee file

### PR DESCRIPTION
**Pull request by AGCooper**
Here is a file containing attendees of the Emory workshop.

### CODE REVIEW

**Review by eefahy — CHANGES_REQUESTED** [review]
Perhaps you could squash these changes into one commit? Or would you rather it get squashed via the UI?

**Comment by AGCooper** [comment]
Where should we squash this? Your end?

**Comment by eefahy** [comment]
Nope. You would do it via `git rebase -i` HURRY!

**Comment by AGCooper** [comment]
AHHH! What is supposed to happen here?

**Comment by eefahy** [comment]
NO

**Pull request closed without merging**
